server:
  port: 9999
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        -   filters:
              - AuthenticationFilter
            id: user-service
            predicates:
              - Path=/user/**
            uri: http://localhost:8082
        -   filters:
              - AuthenticationFilter
            id: profile-service
            predicates:
              - Path=/profile/**
            uri: http://localhost:8081
        -   id: public-profile-content
            predicates:
              - Path=/profile-content/public/{username}
            uri: http://localhost:8086
        -   filters:
              - AuthenticationFilter
            id: profile-content-aggregator-service
            predicates:
              - Path=/profile-content/**
            uri: http://localhost:8086
        -   filters:
              - AuthenticationFilter
            id: block-service
            predicates:
              - Path=/block/**
            uri: http://localhost:8083
        -   id: authentication-service
            predicates:
              - Path=/auth/**
            uri: http://localhost:8085
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: GET, POST, PUT, DELETE, OPTIONS
            allowedHeaders: "*"
            allowCredentials: true